import os
from enum import Enum

from config import Config


class ProjectName(Enum):
    Camel = "camel", "CAMEL"
    Hadoop = "hadoop", "HADOOP"
    Flink = "flink", "FLINK"
    Kafka = "kafka", "KAFKA"
    OpenMeetings = "openmeetings", "OPENMEETINGS"
    Karaf = "karaf", "KARAF"
    Hbase = "hbase", "HBASE"
    Netbeans = "netbeans", "NETBEANS"
    UimaRuta = "uima-ruta", "UIMA"
    Lucene = "lucene-solr", "LUCENE"
    DeltaSpike = "deltaspike", "DELTASPIKE"
    JackrabbitOak = "jackrabbit-oak", "OAK"
    Pulsar = "pulsar", "PULSAR"
    Ofbiz = "ofbiz", "OFBIZ"
    Cayenne = "cayenne", "CAY"
    CommonsCodec = "commons-codec", "CODEC"
    Parquet = "parquet-mr", "PARQUET"
    Kylin = "kylin", "KYLIN"
    Hive = "hive", "HIVE"
    CommonsValidator = "commons-validator", "VALIDATOR"
    Surefire = "maven-surefire", "SUREFIRE"
    Syncope = "syncope", "SYNCOPE"
    CommonsMath = "commons-math", "MATH"
    Tomcat = "tomcat", "MTOMCAT"
    Atlas = "atlas", "ATLAS"
    Struts = "struts", "STR"
    Tika = "tika", "TIKA"
    ServiceComb = "servicecomb-java-chassis", "SCB"
    Ranger = "ranger", "RANGER"
    Cassandra = "cassandra", "CASSANDRA"
    CXF = "cxf", "CXF"
    Avro = "avro", "AVRO"
    Nifi = "nifi", "NIFI"
    Bookkeeper = "bookkeeper", "BOOKKEEPER"
    Clerezza = "clerezza", "CLEREZZA"
    SystemML = "systemml", "SYSTEMML"
    AsterixDB = "asterixdb", "ASTERIXDB"
    Unomi = "unomi", "UNOMI"
    Maven = "maven", "MNG"
    Zeppelin = "zeppelin", "ZEPPELIN"
    CommonsCollections = "commons-collections", "COLLECTIONS"
    Jena = "jena", "JENA"
    Calcite = "calcite", "CALCITE"
    Tez = "tez", "TEZ"
    CommonsLang = "commons-lang", "LANG"
    ActiveMQ = "activemq", "AMQ"
    Curator = "curator", "CURATOR"
    Phoenix = "phoenix", "PHOENIX"
    Samza = "samza", "SAMZA"
    Nutch = "nutch", "NUTCH"
    QpidJMS = "qpid-jms", "QPIDJMS"
    DirectoryKerby = "directory-kerby", "DIRKRB"
    Juneau = "juneau", "JUNEAU"
    MyFacesTobago = "myfaces-tobago", "TOBAGO"
    Isis = "isis", "ISIS"
    Wicket = "wicket", "WICKET"
    Santuario = "santuario-java", "SANTUARIO"
    Helix = "helix", "HELIX"
    Storm = "storm", "STORM"
    Airavata = "airavata", "AIRAVATA"
    MyFaces = "myfaces", "MYFACES"
    CommonsDBCP = "commons-dbcp", "DBCP"
    CommonsVFS = "commons-vfs", "VFS"
    OpenNLP = "opennlp", "OPENNLP"
    Tomee = "tomee", "TOMEE"
    TinkerPop = "tinkerpop", "TINKERPOP"
    DirectoryServer = "directory-server", "DIRSERVER"
    CommonsCompress = "commons-compress", "COMPRESS"
    Accumulo = "accumulo", "ACCUMULO"
    Giraph = "giraph", "GIRAPH"
    Johnzon = "johnzon", "JOHNZON"
    JClouds = "jclouds", "JCLOUDS"
    ManifoldCF = "manifoldcf", "CONNECTORS"
    Shiro = "shiro", "SHIRO"
    Knox = "knox", "KNOX"
    Drill = "drill", "DRILL"
    Crunch = "crunch", "CRUNCH"
    CommonsIO = "commons-io", "IO"
    CommonsCLI = "commons-cli", "CLI"
    Jackrabbit = "jackrabbit", "JCR"
    OpenWebBeans = "openwebbeans", "OWB"
    FOP = "xmlgraphics-fop", "FOP"
    Tajo = "tajo", "TAJO"
    CommonsEmail = "commons-email", "EMAIL"
    DirectoryStudio = "directory-studio", "DIRSTUDIO"
    Tapestry5 = "tapestry-5", "TAP5"
    Archiva = "archiva", "MRM"
    Olingo = "olingo-odata4", "OLINGO"
    OpenJPA = "openjpa", "OPENJPA"
    CommonsJexl = "commons-jexl", "JEXL"
    Roller = "roller", "ROL"
    Reef = "reef", "REEF"

    ActiveMQArtemis = "activemq-artemis", "ARTEMIS"
    Beam = "beam", "BEAM"
    Metron = "metron", "METRON"
    Plc4x = "plc4x", "PLC4X"

    Cocoon = "cocoon", "COCOON"
    CarbonData = "carbondata", "CARBONDATA"
    CommonsCSV = "commons-csv", "CSV"

    CommonsBeanUtils = "commons-beanutils", "BEANUTILS"
    CommonsNet = "commons-net", "NET"
    Continuum = "continuum", "CONTINUUM"


    # Projects that failed selection
    # new
    # Groovy = "groovy", "GROOVY"
    # Ignite = "ignite", "IGNITE"
    # Bahir = "bahir", "BAHIR"
    # CommonsDigester = "commons-digester", "DIGESTER"
    # CommonsDaemon = "commons-daemon", "DAEMON"
    # Buildr = "buildr", "BUILDR"
    # Click = "click", "CLK"
    # Aries = "aries", "ARIES"
    # Bigtop = "bigtop", "BIGTOP"
    # VXQuery = "vxquery", "VXQUERY"
    # Brooklyn = "incubator-brooklyn", "BROOKLYN"
    # CloudStack = "cloudstack", "CLOUDSTACK"
    # CommonsCrypto = "commons-crypto", "CRYPTO"
    # GeodeBenchmarks = "geode-benchmarks", "GEODE"
    # Mina = "mina", "DIRMINA"
    # Submarine = "submarine", "SUBMARINE"
    # Griffin = "griffin", "GRIFFIN"
    # CommonsImaging = "commons-imaging", "IMAGING"
    # RocketMQ = "rocketmq", "ROCKETMQ"
    # Synapse = "synapse", "SYNAPSE"
    # Fineract = "fineract", "FINERACT"
    # Dubbo = "dubbo", "DUBBO"

    def github(self):
        return self.value[0]

    def jira(self):
        return self.value[1]

    def path(self):
        return os.path.join(Config().config['REPO']['RepoDir'], self.value[0])

